# Generated by Django 3.2.5 on 2021-07-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.classes'),
        ),
        migrations.AlterField(
            model_name='classandpayment',
            name='pcc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.pcc'),
        ),
        migrations.AlterField(
            model_name='classandpayment',
            name='to_time',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='feesreport',
            name='batch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sectionorbatch'),
        ),
        migrations.AlterField(
            model_name='feesreport',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.classes'),
        ),
        migrations.AlterField(
            model_name='students',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='fathersMobile',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='fathersName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='fathersProfession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mothersMobile',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mothersName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mothersProfession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='parmanentAddress',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='presentAddress',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='baCGPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='baPassingYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='baSubject',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='baUniversity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='currentInstitute',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='emergencyMobileNumber',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='hscBoard',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='hscGPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='hscGroup',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='hscPassingYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='mobileNumber',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='parmanentAddress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='presentAddress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sscBoard',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sscGPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sscGroup',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sscPassingYear',
            field=models.IntegerField(null=True),
        ),
    ]
