# Generated by Django 3.2.5 on 2021-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20210714_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject_exam_marks',
            field=models.IntegerField(default=0),
        ),
    ]
