# Generated by Django 3.2.5 on 2021-07-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_studentresult_subject_exam_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_marks', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.examination')),
            ],
        ),
    ]
