# Generated by Django 3.2.5 on 2021-07-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_totalmarks_obtained_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='gpa',
            field=models.FloatField(null=True),
        ),
    ]
