# Generated by Django 3.2.5 on 2021-07-17 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_studentresult_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalmarks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalmarks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
