# Generated by Django 3.2.5 on 2021-07-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20210717_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExpenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='totalmarks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='totalmarks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
