# Generated by Django 3.2.5 on 2021-07-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_auto_20210720_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalexpenses',
            name='date',
            field=models.DateField(),
        ),
    ]
