# Generated by Django 3.2.5 on 2021-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_auto_20210804_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
