# Generated by Django 3.2.5 on 2021-08-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_auto_20210805_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
