# Generated by Django 3.2.5 on 2021-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0019_examination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
