# Generated by Django 3.2.5 on 2021-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_studentresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalmarks',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
