# Generated by Django 3.2.5 on 2021-08-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_totalmarks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='totalmarks',
            name='status',
        ),
    ]
