# Generated by Django 3.2.6 on 2021-08-06 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0023_examination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'Student'), (4, 'Accountant')], default=1, max_length=10),
        ),
        migrations.CreateModel(
            name='Accountants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presentAddress', models.TextField(null=True)),
                ('parmanentAddress', models.TextField(null=True)),
                ('mobileNumber', models.CharField(max_length=14, null=True)),
                ('emergencyMobileNumber', models.CharField(max_length=14, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('experience', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
