# Generated by Django 3.2.6 on 2021-08-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0024_auto_20210806_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstudent',
            name='in_cash',
            field=models.IntegerField(default=0),
        ),
    ]
