# Generated by Django 3.2.6 on 2021-08-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0025_paymentstudent_in_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstudent',
            name='batch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sectionorbatch'),
        ),
        migrations.AddField(
            model_name='paymentstudent',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.classes'),
        ),
    ]
