# Generated by Django 3.2.6 on 2021-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0026_auto_20210810_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalmarks',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
