# Generated by Django 3.2.6 on 2021-08-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0028_totalmarks_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmarks',
            name='exam_date',
            field=models.DateField(),
        ),
    ]
