# Generated by Django 3.2.6 on 2021-08-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0033_alter_studentresult_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
