# Generated by Django 3.2.6 on 2021-08-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0034_pdfdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstudent',
            name='fees_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.feesreport'),
        ),
        migrations.AlterField(
            model_name='pdfdetails',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
