# Generated by Django 3.2.6 on 2021-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0035_auto_20210813_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesreport',
            name='fees_title',
            field=models.CharField(default='Fees Of ', max_length=25),
        ),
        migrations.AddField(
            model_name='feesreport',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feesreport',
            name='paid_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feesreport',
            name='fees_date',
            field=models.DateTimeField(null=True),
        ),
    ]
