# Generated by Django 3.2.6 on 2021-08-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0036_auto_20210813_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesreport',
            name='action',
            field=models.IntegerField(default=0),
        ),
    ]
