# Generated by Django 3.2.6 on 2021-08-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0037_feesreport_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesreport',
            name='bkash_nmb',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='feesreport',
            name='in_cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feesreport',
            name='trans_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
