# Generated by Django 3.2.6 on 2021-08-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0038_auto_20210814_0131'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='students',
            name='feesAmount',
            field=models.IntegerField(default=1500),
        ),
    ]
