# Generated by Django 3.2.6 on 2021-08-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0042_alter_students_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionorbatch',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.classes'),
        ),
    ]
