# Generated by Django 3.2.6 on 2021-08-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0043_sectionorbatch_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
