# Generated by Django 3.2.6 on 2021-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0045_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
