# Generated by Django 3.2.6 on 2021-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0046_teachers_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classandpayment',
            name='class_date',
            field=models.CharField(max_length=255),
        ),
    ]
