# Generated by Django 3.2.6 on 2021-08-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0050_subjects_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='batch_id',
        ),
    ]
