# Generated by Django 3.2.6 on 2021-08-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0052_subjects_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesreport',
            name='fees_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feesreport',
            name='fees_title',
            field=models.CharField(max_length=25),
        ),
    ]
