# Generated by Django 3.2.6 on 2021-08-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0053_auto_20210820_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
