# Generated by Django 3.2.6 on 2021-08-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0055_alter_onlineclass_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
    ]
