# Generated by Django 3.2.6 on 2021-08-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0057_customsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject_assignment_marks',
            field=models.IntegerField(default=0),
        ),
    ]
