# Generated by Django 3.2.6 on 2021-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0058_alter_studentresult_subject_assignment_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='smsMobile',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
