# Generated by Django 3.2.6 on 2021-12-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0059_students_smsmobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesreport',
            name='extra_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='feesreport',
            name='extra_fees_title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
