# Generated by Django 3.2.6 on 2021-12-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0060_auto_20211226_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='batch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sectionorbatch'),
        ),
        migrations.AlterField(
            model_name='students',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.classes'),
        ),
    ]
