# Generated by Django 4.0.7 on 2022-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0066_alter_feesreport_extra_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='monthly_payment',
            field=models.BooleanField(default=False),
        ),
    ]
