# Generated by Django 4.0.7 on 2022-09-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0067_teachers_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='monthly_payment_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='monthly_payment',
            field=models.IntegerField(default=0),
        ),
    ]
