# Generated by Django 4.0.7 on 2022-09-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0068_teachers_monthly_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_teacher',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
